-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le :  mer. 15 jan. 2020 à 14:38
-- Version du serveur :  10.4.10-MariaDB
-- Version de PHP :  7.4.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `blog`
--
CREATE DATABASE IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `blog`;

-- --------------------------------------------------------

--
-- Structure de la table `admin`
--

DROP TABLE IF EXISTS `admin`;
CREATE TABLE IF NOT EXISTS `admin` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `fk_admin_user1_idx` (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `admin`
--

INSERT INTO `admin` (`id`, `user_id`) VALUES
(1, 1);

-- --------------------------------------------------------

--
-- Structure de la table `comment`
--

DROP TABLE IF EXISTS `comment`;
CREATE TABLE IF NOT EXISTS `comment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `author` varchar(25) NOT NULL,
  `email` varchar(100) NOT NULL,
  `commContent` varchar(255) NOT NULL,
  `created_date` datetime NOT NULL,
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `post_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `fk_comment_post1_idx` (`post_id`),
  KEY `fk_comment_user1_idx` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Structure de la table `post`
--

DROP TABLE IF EXISTS `post`;
CREATE TABLE IF NOT EXISTS `post` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `img` varchar(45) NOT NULL,
  `title` text NOT NULL,
  `postContent` longtext NOT NULL,
  `detail` varchar(255) NOT NULL,
  `statut` varchar(20) NOT NULL,
  `created_date` datetime NOT NULL DEFAULT current_timestamp(),
  `update_time` datetime NOT NULL DEFAULT current_timestamp(),
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `fk_post_user1_idx` (`user_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=49 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `post`
--

INSERT INTO `post` (`id`, `img`, `title`, `postContent`, `detail`, `statut`, `created_date`, `update_time`, `user_id`) VALUES
(4, 'https://pic.clubic.com/v1/images/1421188/raw?', 'Article 1', 'Le groupe AT&amp;T pourrait céder la part de la société Hulu qu\'il détient via sa filiale WarnerMedia, ce qui pourrait précipiter le rachat définitif par Disney du spécialiste de la VoD.\r\n&lt;p&gt;Alors que Disney va lancer sa plateforme de streaming dans les prochains mois et que la firme américaine est sur le point de finaliser le rachat de la Fox, la société pourrait voir ses chances d\'avaler Hulu grandir assez rapidement. C\'est lors d\'une conférence téléphonique donnée par des représentants de AT&amp;T (qui possède une part minoritaire de Hulu) jeudi dernier que The Walt Disney Company a pu apprendre la bonne nouvelle.\r\nLa dette qui plombe AT&amp;T pourrait aider Disney.\r\nIl y a quelques jours, comme le rapporte The Information, le groupe AT&amp;T a annoncé qu\'il « envisageait de vendre sa participation de 10 % dans Hulu dans le cadre d\'une analyse d\'actifs plus large visant à  réduire sa dette ». Pour ne pas être trop perdu, faisons un bref rappel de la composition du capital du concurrent de Netflix. Comcast, la Fox et Disney détiennent chacun 30 % du capital de Hulu. Les 10 % restants appartiennent à  WarnerMedia, filiale de AT&amp;T.\r\n', 'Hulu, concurrent de Netflix, pourrait définitivemet basculer dans le giron de Disney', '1', '2019-08-24 00:00:00', '2020-01-14 19:01:24', 1),
(2, 'https://pic.clubic.com/v1/images/1688024/raw?', 'Article 2\r\n', '\"La finalisation de l\'achat des actifs de Fox par Disney donnera déjà  le contrôle de Hulu à  Mickey, qui n\'en demandait pas tant lorsqu\'il a aussi appris que Comcast pourrait être poussé à  céder ses parts, refusant de rester dans une position minoritaire. Alors, s\'il s\'avère que AT&T veut bel et bien là¢cher Hulu, il faut maintenant se demander à  quel prix. En effet, depuis sa montée au capital en 2016 et après un investissement ultérieur, Warner a dépensé 800 millions de dollars dans Hulu.\r\nHulu dans le giron de Disney : un danger pour Netflix,\r\nSelon les médias américains, un récent document réglementaire indiquerait que Warner peut remettre sa participation à  Hulu à  tout moment jusqu\'au mois d\'aoà»t de l\'année prochain, sous certaines conditions. Reste à  savoir maintenant si la dette revendiquée par AT&T (après avoir racheté Time Warner pour 84,5 milliards de dollars) pourrait être suffisante pour satisfaire à  ces « certaines conditions ». A défaut, AT&T n\'aura pas l\'avantage dans les négociations.\"\r\n', 'Hulu dans le giron de Disney : un danger pour Netflix\r\n', '1', '2019-08-24 10:42:00', '2019-08-26 13:30:00', 2),
(17, 'https://pic.clubic.com/v1/images/1421188/raw?', 'Article 3\r\n', 'Le groupe AT&T pourrait céder la part de la société Hulu qu\'il détient via sa filiale WarnerMedia, ce qui pourrait précipiter le rachat définitif par Disney du spécialiste de la VoD.\r\n<p>Alors que Disney va lancer sa plateforme de streaming dans les prochains mois et que la firme américaine est sur le point de finaliser le rachat de la Fox, la société pourrait voir ses chances d\'avaler Hulu grandir assez rapidement. C\'est lors d\'une conférence téléphonique donnée par des représentants de AT&T (qui possède une part minoritaire de Hulu) jeudi dernier que The Walt Disney Company a pu apprendre la bonne nouvelle.\r\nLa dette qui plombe AT&T pourrait aider Disney.\r\nIl y a quelques jours, comme le rapporte The Information, le groupe AT&T a annoncé qu\'il « envisageait de vendre sa participation de 10 % dans Hulu dans le cadre d\'une analyse d\'actifs plus large visant à  réduire sa dette ». Pour ne pas être trop perdu, faisons un bref rappel de la composition du capital du concurrent de Netflix. Comcast, la Fox et Disney détiennent chacun 30 % du capital de Hulu. Les 10 % restants appartiennent à  WarnerMedia, filiale de AT&T.\r\n', 'Hulu, concurrent de Netflix, pourrait définitivemet basculer dans le giron de Disney\r\n', '1', '2019-08-24 00:00:00', '2019-08-28 00:00:00', 1),
(12, 'https://pic.clubic.com/v1/images/1421188/raw?', 'Article 5', 'Le groupe AT&T pourrait céder la part de la société Hulu qu\'il détient via sa filiale WarnerMedia, ce qui pourrait précipiter le rachat définitif par Disney du spécialiste de la VoD.\r\n<p>Alors que Disney va lancer sa plateforme de streaming dans les prochains mois et que la firme américaine est sur le point de finaliser le rachat de la Fox, la société pourrait voir ses chances d\'avaler Hulu grandir assez rapidement. C\'est lors d\'une conférence téléphonique donnée par des représentants de AT&T (qui possède une part minoritaire de Hulu) jeudi dernier que The Walt Disney Company a pu apprendre la bonne nouvelle.\r\nLa dette qui plombe AT&T pourrait aider Disney.\r\nIl y a quelques jours, comme le rapporte The Information, le groupe AT&T a annoncé qu\'il « envisageait de vendre sa participation de 10 % dans Hulu dans le cadre d\'une analyse d\'actifs plus large visant à  réduire sa dette ». Pour ne pas être trop perdu, faisons un bref rappel de la composition du capital du concurrent de Netflix. Comcast, la Fox et Disney détiennent chacun 30 % du capital de Hulu. Les 10 % restants appartiennent à  WarnerMedia, filiale de AT&T.\r\n', 'Hulu, concurrent de Netflix, pourrait définitivemet basculer dans le giron de Disney\r\n\r\n', '1', '2019-08-25 00:00:00', '2019-08-15 11:20:00', 1),
(10, 'https://pic.clubic.com/v1/images/1688024/raw?', 'Article 6', '\"La finalisation de l\'achat des actifs de Fox par Disney donnera déjà  le contrôle de Hulu à  Mickey, qui n\'en demandait pas tant lorsqu\'il a aussi appris que Comcast pourrait être poussé à  céder ses parts, refusant de rester dans une position minoritaire. Alors, s\'il s\'avère que AT&T veut bel et bien là¢cher Hulu, il faut maintenant se demander à  quel prix. En effet, depuis sa montée au capital en 2016 et après un investissement ultérieur, Warner a dépensé 800 millions de dollars dans Hulu.\r\nHulu dans le giron de Disney : un danger pour Netflix,\r\nSelon les médias américains, un récent document réglementaire indiquerait que Warner peut remettre sa participation à  Hulu à  tout moment jusqu\'au mois d\'aoà»t de l\'année prochain, sous certaines conditions. Reste à  savoir maintenant si la dette revendiquée par AT&T (après avoir racheté Time Warner pour 84,5 milliards de dollars) pourrait être suffisante pour satisfaire à  ces « certaines conditions ». A défaut, AT&T n\'aura pas l\'avantage dans les négociations.\"\r\n', 'Hulu dans le giron de Disney : un danger pour Netflix\r\n', '1', '2019-08-25 00:00:00', '2019-08-15 11:20:00', 2),
(8, 'https://pic.clubic.com/v1/images/1688024/raw?', 'Article 8', '\"La finalisation de l\'achat des actifs de Fox par Disney donnera déjà  le contrôle de Hulu à  Mickey, qui n\'en demandait pas tant lorsqu\'il a aussi appris que Comcast pourrait être poussé à  céder ses parts, refusant de rester dans une position minoritaire. Alors, s\'il s\'avère que AT&T veut bel et bien là¢cher Hulu, il faut maintenant se demander à  quel prix. En effet, depuis sa montée au capital en 2016 et après un investissement ultérieur, Warner a dépensé 800 millions de dollars dans Hulu.\r\nHulu dans le giron de Disney : un danger pour Netflix,\r\nSelon les médias américains, un récent document réglementaire indiquerait que Warner peut remettre sa participation à  Hulu à  tout moment jusqu\'au mois d\'aoà»t de l\'année prochain, sous certaines conditions. Reste à  savoir maintenant si la dette revendiquée par AT&T (après avoir racheté Time Warner pour 84,5 milliards de dollars) pourrait être suffisante pour satisfaire à  ces « certaines conditions ». A défaut, AT&T n\'aura pas l\'avantage dans les négociations.\"\r\n', 'Hulu dans le giron de Disney : un danger pour Netflix\r\n', '1', '2019-08-25 00:00:00', '2019-08-15 11:20:00', 2),
(7, 'https://pic.clubic.com/v1/images/27793/raw?', 'Reprehenderit porro maxime.', 'Corporis et laboriosam nihil quidem ut. Vitae officiis voluptas qui incidunt exercitationem. Omnis et officia enim atque maiores consequatur consequatur. Doloribus et est harum dignissimos. Voluptatem ipsum fugit praesentium dolorem repellat quisquam. Sit et et nam velit quo. Voluptas qui neque maiores voluptatem reiciendis fugit architecto. Quidem autem illo inventore sunt. Earum aliquam qui dolore perferendis ea cupiditate accusamus. Dolorem ipsum minima sint id quisquam porro. Et natus expedita ea at ipsum architecto dolore. Dolor autem enim quia est nesciunt esse laborum. Quidem in a id debitis minus. Consequuntur consequuntur minus a sed cum. Ut tenetur sed nobis accusantium. Perspiciatis et est laborum dolorem vitae culpa. Quis saepe quia natus autem pariatur occaecati.', 'Eum praesentium maiores velit aut voluptates. Quidem esse eveniet dicta molestiae aut exercitationem repellat. Ut officia in consectetur quia rerum aliquam voluptatem.', '1', '2020-01-15 10:40:24', '2020-01-15 10:40:24', 8),
(9, 'https://pic.clubic.com/v1/images/82347/raw?', 'Est ducimus sunt.', 'Tenetur aliquam possimus tenetur iusto dolorem quae. Aut non magnam quis. Similique est non veniam omnis eligendi unde provident. Distinctio molestiae eveniet sit autem autem hic. At voluptas consectetur voluptatem numquam. Dolore et dolores animi aut unde officiis. Ea quisquam numquam voluptatibus ducimus pariatur est aut. Provident ex fugit eos dolore sit autem itaque. Occaecati eveniet est consequuntur sed architecto eveniet exercitationem saepe. Delectus nulla voluptatem odio consequuntur. Quo dolorem hic neque distinctio. Nobis recusandae sit sit. Necessitatibus quisquam ut rerum deleniti dolor architecto. Maiores in velit rem et saepe animi est quae. Aspernatur minima voluptatem cupiditate repellendus quae est aut.', 'Reiciendis quod rem magnam voluptas ex aliquam. Quo sit iste necessitatibus cupiditate autem voluptatem omnis.', '1', '2020-01-15 10:40:24', '2020-01-15 10:40:24', 5),
(18, 'https://pic.clubic.com/v1/images/71769/raw?', 'Non eum natus qui.', 'Ex dolor doloremque suscipit aut. Dolorem quis quos quia sunt cumque. Dolores molestiae deleniti quod perspiciatis. Quis debitis laudantium dolorem dolor officia corrupti ducimus nostrum. Amet ad quis non molestias fugiat deserunt reprehenderit. Culpa aperiam repellendus a est debitis officiis eos animi. Laboriosam quaerat voluptas consequatur dicta numquam minus earum omnis. Illo aut rerum quia ipsum fugit eos reprehenderit. Explicabo id rerum maxime voluptates rerum dolor est voluptatibus. Est sit est optio distinctio unde. Dolore omnis ipsam hic tempora. Et minima nihil laborum incidunt nihil sequi velit. Ducimus magnam necessitatibus facilis reprehenderit reprehenderit sed. Harum quibusdam numquam inventore ipsam. Molestiae est eveniet et quia. Suscipit et voluptatem est dolorem esse. Vel incidunt consequatur voluptatem veniam illo quia et. Voluptas quo blanditiis asperiores et incidunt. Ab sunt ipsa placeat dignissimos quod aut sint. Omnis et consequatur sed delectus doloremque. Temporibus nemo qui excepturi provident amet. Sint temporibus repellat aut aperiam perferendis.', 'Nobis voluptatem repudiandae et repellat commodi voluptas. Et amet omnis et omnis. Aliquid vero eligendi aut corrupti.', '1', '2020-01-15 10:43:14', '2020-01-15 10:43:14', 27),
(1, 'https://pic.clubic.com/v1/images/81587/raw?', 'Quis vel blanditiis sit qui.', 'Sint est distinctio aut sint vel cum commodi dolorem. Quo asperiores optio quo autem. Molestiae accusamus quas aspernatur reiciendis non pariatur. At est sint molestiae molestias. Ut rerum dolorum exercitationem quos quo eos. In ad tempore hic dolorem hic ipsam debitis. Quia laudantium aliquam consequatur. Dolor nesciunt ducimus rem aut consequatur sit est. Atque non nihil deleniti. Nemo iste et facere qui. Culpa ipsam saepe quisquam laboriosam. Et velit provident omnis odio enim voluptas quas. Molestiae sint ratione esse maxime voluptas voluptas. Est nulla suscipit eveniet nobis provident voluptatem consequuntur. Quasi ipsum voluptas omnis reprehenderit. Corporis aperiam laboriosam repudiandae aperiam tenetur.', 'Dolorem fugit possimus et qui nulla est qui. Ipsam minus quia accusamus et quaerat. Voluptatibus iusto laudantium velit sed.', '1', '2020-01-15 10:43:14', '2020-01-15 10:43:14', 50),
(20, 'https://pic.clubic.com/v1/images/61079/raw?', 'Eos repudiandae eos quo.', 'Molestiae sunt laboriosam qui reprehenderit. Quia non corrupti officia quaerat. Explicabo aut ducimus eum eveniet quasi nostrum. Sunt tenetur iste non corrupti minima. Saepe et ex aut corrupti optio. Autem ut aut quam voluptatem eius perferendis totam. Voluptatem voluptate sit nemo dignissimos libero et et ratione. Nemo nisi sit a id eligendi ea numquam. Accusamus voluptate voluptas non. Repellat ut sint vel est non laborum. Est nisi quia labore autem laudantium. Enim libero est et omnis quae ut. Velit id iure provident. Voluptates accusantium quibusdam cupiditate doloremque eos excepturi. Animi corrupti perspiciatis repellat. Sit reprehenderit autem officia dolores voluptatem.', 'Ex tenetur perspiciatis veritatis expedita maxime voluptas. Quos neque hic ut possimus. Aut perspiciatis quo error quaerat quo repellat quae.', '1', '2020-01-15 10:43:14', '2020-01-15 10:43:14', 13),
(13, 'https://pic.clubic.com/v1/images/29101/raw?', 'Natus dolor aut.', 'Quae nostrum vitae dolor rem temporibus. Laboriosam voluptatem corporis possimus earum aliquid aut. At repellat adipisci sit omnis veniam doloremque. Eligendi modi ut nihil commodi modi. Corporis eaque sed est fuga dolores pariatur. Quaerat fugit modi et aut aut earum rerum et. Voluptas adipisci quasi soluta. Distinctio tempora dolorum et omnis sunt voluptas doloribus qui. Sed qui quia nobis praesentium corporis. Unde ipsa facilis adipisci adipisci modi. Aliquid unde magnam labore qui voluptate. Quis error quisquam praesentium voluptatem. Aut libero fugiat cupiditate ipsa harum. Et ea eveniet doloremque enim sit nisi. Illo amet sed magni rerum sed. Dolorum qui omnis aut omnis aut. Voluptatem quasi consequuntur omnis. Dolores deleniti dignissimos quam eos in expedita. Qui ea dicta pariatur veritatis. Veritatis nesciunt harum ea blanditiis voluptatibus ullam.', 'Saepe id possimus porro id voluptatum optio aut. Odio et tempora cumque cum eum.', '1', '2020-01-15 10:40:24', '2020-01-15 10:40:24', 12),
(3, 'https://pic.clubic.com/v1/images/823669/raw?', 'Incidunt quo ducimus.', 'Eos et fugiat eos esse praesentium et esse occaecati. Excepturi esse dolores hic sunt voluptatem non doloribus. Aliquam numquam et sequi sunt. Sed expedita eius veniam sed. Ut corrupti aut eius porro. Officia molestiae in voluptas aut perferendis. Minus nam qui perferendis aspernatur. Mollitia et nisi perferendis expedita. Ut cumque aperiam eligendi molestias consequuntur voluptates mollitia. In commodi dolore quod quia quia numquam. Exercitationem itaque aliquam dolorum impedit. Laudantium tempora laboriosam totam quibusdam quibusdam sed. Sunt corporis nam cupiditate et vero. Molestiae veritatis totam eaque nemo ratione. Sunt voluptatum iure natus qui provident. Dolorem et enim voluptatibus delectus est optio enim inventore. Tempora ut nemo sit sed nobis est delectus. Culpa aut et molestiae aliquid aut. Voluptas est rerum et accusamus nobis nihil. Vero eos ea aut unde vitae. Commodi blanditiis et accusantium autem.', 'Voluptatem iusto error eligendi ad expedita odio. Dolorem commodi distinctio distinctio facere quis est minus maxime. Rerum expedita ut reiciendis inventore laudantium.', '1', '2020-01-15 10:45:22', '2020-01-15 10:45:22', 46),
(14, 'https://pic.clubic.com/v1/images/14853/raw?', 'Fugiat placeat aliquid.', 'Et fugit dolores aut soluta minus consectetur labore. Eos atque temporibus et error quia quia eligendi. Similique impedit aperiam aut deleniti dolor ipsam. Atque explicabo ut saepe. Nam asperiores est et est dicta. Voluptas voluptatibus ipsam nihil voluptas eveniet dicta. Similique debitis sed ad nostrum nisi. Ad autem commodi blanditiis ut facere qui molestias ut. Ut voluptas deleniti consequatur. Quisquam sit nam et quia. Dolor velit tempore quia. Architecto ratione sint qui qui deserunt voluptatem omnis. Impedit et aut omnis eius quia. Accusantium assumenda voluptatem ipsa fugit autem impedit. Voluptatem ut aut aut repellat. Aliquid corporis dignissimos facere qui assumenda. Similique est repudiandae voluptas et illum fugiat ipsa. Ut pariatur et quam adipisci corrupti eum. Ut ex ab delectus qui consequatur praesentium.', 'Tempora officia sint doloribus corporis est harum placeat. Aut quae perspiciatis qui ullam. Praesentium voluptatem iusto dolorum aut illo tempore totam.', '1', '2020-01-15 10:43:14', '2020-01-15 10:43:14', 25),
(11, 'https://pic.clubic.com/v1/images/69567/raw?', 'Ea commodi rerum vitae.', 'Laboriosam facilis molestiae repudiandae et qui. Recusandae dicta quod cupiditate fuga labore totam. Eum et reiciendis aut quia excepturi eius. Aliquid qui modi dolores quo. Est nemo voluptatem dolor odit. Et fugiat aut aliquam eius earum. Sed consequatur optio ad non ullam eum debitis et. Et ut voluptas expedita. Officia ducimus qui molestias. Iste nemo veritatis illum impedit sit minus eum. Aspernatur sunt possimus nemo et praesentium dolor. Voluptatem aut et mollitia quis suscipit et. Consectetur omnis autem vel expedita quidem magnam. Et adipisci reprehenderit exercitationem id consequatur distinctio voluptate maxime. Natus libero eum assumenda. Sed et possimus et molestiae eum consequuntur autem ipsam. Ipsa iusto vel nobis debitis et ipsa provident. Placeat tempora dolores illo iure tempore aliquid. Itaque perspiciatis fugit fugiat distinctio aut. Debitis dolores numquam dolore qui consequatur ut. Facere aut ad est quisquam quia. Adipisci quos libero dolorem dicta qui ut ipsa id. Sed quisquam itaque quibusdam consectetur. Perspiciatis dolores doloremque corporis veniam commodi maiores.', 'Eum praesentium odit culpa. Ut est eveniet voluptas voluptatem recusandae possimus vitae.', '1', '2020-01-15 10:40:24', '2020-01-15 10:40:24', 24),
(19, 'https://pic.clubic.com/v1/images/179843/raw?', 'Doloribus ut iure eius.', 'Nihil officiis aut ut et quae nam. Neque voluptas et expedita explicabo quod nulla. Ab ea nihil illo accusamus nihil nobis porro. Quia vitae possimus pariatur quasi impedit. Iure dolor debitis perferendis quo et vero. Architecto unde rerum aut enim. Et illum ut et aliquid omnis. Nostrum adipisci culpa mollitia autem. Numquam corrupti eum facere ut accusamus dolor et. Quibusdam aliquam officiis earum aut illo. Quam qui qui magni autem et numquam. Dolorem quos qui impedit libero neque amet placeat deleniti. Unde quo qui enim. Dignissimos voluptatem deserunt non ipsam ullam quia ut. Eos repellat ipsam ut non. Quia a dignissimos atque impedit porro laudantium repellendus sunt. Adipisci illo sint eaque blanditiis nesciunt non. Tempore tempora cumque architecto. Magnam voluptas non voluptatem voluptatem. Ducimus omnis fuga nulla sit. Omnis quod adipisci et consequatur est et cupiditate.', 'Totam sed magni deserunt odio ipsum reprehenderit omnis. Et iure earum beatae dolorum et aut. Assumenda pariatur laudantium nulla voluptas voluptates voluptatum rerum.', '1', '2020-01-15 10:45:22', '2020-01-15 10:45:22', 27),
(21, 'https://pic.clubic.com/v1/images/20505/raw?', 'Similique enim eum aperiam.', 'Reiciendis facilis consectetur molestias maxime officia. Sed distinctio harum sapiente nulla. Vel ratione velit distinctio dolorem vitae temporibus. Odio blanditiis sequi iure itaque. Magnam nihil assumenda eveniet quia. Odio nemo iusto beatae rerum. Quo sed cupiditate aliquid provident. Quos rerum vero accusamus dolore ipsum iusto expedita. Aut aliquam quam repellat ea voluptatem aut asperiores. Consequatur quo aliquid voluptatum dolores velit aut. Neque error voluptas iure est blanditiis totam perferendis sed. Distinctio ipsa officia sunt natus et laboriosam consectetur. Qui distinctio odio ipsam sint. Soluta laudantium aliquam at dolore tempora minus libero in. Nisi dolore et fugiat. Ex eum vel autem harum ipsam ea eos. Unde sit beatae nostrum sunt vel aliquid. Minima neque repellat corporis nobis et. Eos perferendis nihil molestiae quis illo. Nisi voluptatem tempore repellat quia delectus et. Repellendus fugit aut veniam adipisci est incidunt nisi. Et dolores voluptas amet officia.', 'Nam consequuntur assumenda quia inventore quidem quos. Sed necessitatibus minus ducimus et error molestias. Quia ea est assumenda et ut quis dolores est.', '1', '2020-01-15 10:40:24', '2020-01-15 10:40:24', 23),
(5, 'https://pic.clubic.com/v1/images/946995/raw?', 'Ex animi at mollitia.', 'Odio corporis velit ea repellendus voluptatibus corporis quos. Est quaerat similique quis totam eligendi. Nemo maiores nihil et doloremque rem. Quas eos hic tempore rerum qui pariatur in. Id illum quia voluptas saepe. Nihil consequatur et neque sequi. Qui perspiciatis velit est tenetur. Quia ea dolore quis. Vero aut molestiae beatae sit. Mollitia rerum aut ab inventore sunt eligendi dolorum. In vitae est aliquid deserunt expedita ea ea. Harum quis necessitatibus dolorum. Quo repudiandae veniam ut quo. Modi dolorem quo dolor est. Maxime asperiores numquam voluptas quo et ratione aut. Fuga minima rerum est animi. Cumque et at voluptate dolores necessitatibus ab. Unde sed quis maiores quia qui saepe. Voluptas ea dolorum dignissimos vel laborum assumenda modi. Ex consequatur quas sunt est et.', 'Ad quo dolorem sint vero omnis quia. Ducimus ab porro accusamus voluptatem voluptatem amet et. Perferendis recusandae nostrum et praesentium laudantium mollitia perspiciatis.', '1', '2020-01-15 10:45:22', '2020-01-15 10:45:22', 15),
(6, 'https://pic.clubic.com/v1/images/399299/raw?', 'Non recusandae.', 'Maiores quia itaque cum. Mollitia aut totam unde. Optio sint tenetur facere officia inventore. Consequuntur ratione sed et modi odio nesciunt. Delectus tempora maxime molestias ipsa sit occaecati. Aliquid ad ratione nemo aperiam quo sed veritatis nemo. Iusto assumenda est asperiores et. Eveniet aperiam non voluptatem explicabo esse commodi rerum libero. Dolore sint ipsa qui voluptates. Et saepe sed aut ratione et. Vitae voluptates consequuntur laudantium eveniet. Dicta accusamus et nam temporibus et quia. Rem dolor aspernatur dolorem veniam sint nam. Laborum velit culpa quia rerum. Cum praesentium quia et. Deleniti quia omnis voluptates non fugit nesciunt consequatur. Ea non est et hic recusandae praesentium quia. Eaque fuga dolor assumenda consequatur excepturi dicta. Et aut ex eveniet est et repudiandae rerum. Nemo quas sed harum temporibus iusto. Nihil soluta iusto corrupti rem. Cumque quod delectus tempore soluta rem adipisci excepturi. Sed velit harum maiores voluptatibus. Velit vel voluptate voluptatibus repudiandae dolore sunt. Magnam eveniet placeat officiis aut assumenda veniam. Sapiente occaecati in est dicta quo aut qui possimus.', 'Dolores quo asperiores aut accusamus alias. Est molestiae doloribus aut. Aliquam ut dolorem soluta aut maiores et.', '1', '2020-01-15 10:45:22', '2020-01-15 10:45:22', 33),
(15, 'https://pic.clubic.com/v1/images/986501/raw?', 'Delectus quia officia.', 'Quia doloremque quia quidem explicabo. Ut consequatur odio est est aut doloribus. Repellat ut vel omnis non et repellat. Repudiandae illum atque aut commodi ut alias nemo nam. Qui porro quo illum ea. Occaecati quidem voluptas id alias. Accusantium esse voluptatum esse omnis accusantium nemo voluptas magnam. Est et dolores asperiores nisi placeat omnis tempora. Modi animi nam magnam omnis similique provident dolorum quia. Aut ut deleniti facilis quaerat. Sint impedit perferendis natus ea est omnis ut. Aliquid repellendus consequatur aut quo. Veniam sit consequatur atque numquam error. Debitis similique quibusdam ea omnis. Ut provident ut aut. Eveniet nihil doloremque quaerat magni. Officiis eius at nihil et ratione ut non. Voluptates iusto eos minima eos.', 'Fuga non amet eaque. Accusantium alias nihil minima.', '1', '2020-01-15 10:45:22', '2020-01-15 10:45:22', 46),
(16, 'https://pic.clubic.com/v1/images/674251/raw?', 'Facilis dolorem.', 'Iste et pariatur laborum sapiente consequatur quaerat. Porro molestias aut voluptas. Eos consequatur eum quas ullam. Est officiis voluptatum occaecati et quas sit soluta debitis. Sunt aspernatur ducimus consequatur. Quo molestias et sed hic. Quia laborum sint itaque perferendis et est. Sequi veniam aliquam voluptas reiciendis laboriosam. Sed aut amet voluptas itaque repellendus ut ipsum. Consectetur quia temporibus sed. Et deserunt sit praesentium ut vitae. In quidem voluptates labore saepe voluptates iste veritatis. Ab ut quo et dicta ut quod natus. Distinctio aut voluptatum minus fugit earum veritatis. Voluptatem quam velit ducimus aut id illum qui. Qui quas perspiciatis ipsum architecto distinctio. Dolorum repellendus et vel tenetur. Rerum velit quas temporibus sit quo. Rem illo et quidem tempora unde a quae. Sint tempore porro nihil quis distinctio. Voluptates quis molestiae harum pariatur voluptates ullam quo. Sed illum voluptatem quis eum. Voluptatem maxime non quia est neque dolor sint. Quas voluptatum quo occaecati alias modi. Unde ut et laborum velit nesciunt. Quas laudantium delectus ipsa voluptatum. Aperiam tempora omnis alias quis id.', 'Adipisci porro modi beatae omnis. Quam accusamus dicta quia optio qui quod hic nam.', '1', '2020-01-15 10:45:22', '2020-01-15 10:45:22', 26),
(39, 'https://pic.clubic.com/v1/images/794085/raw?', 'Occaecati rem aut.', 'Ut molestias aut odio voluptates. Cumque nobis eum fuga dolorum nobis aut. Deserunt voluptatum facere et. Voluptate quas error exercitationem aut nihil quos. Sed veniam autem commodi facere dolor. Culpa voluptates tempora voluptatem est laboriosam architecto. Incidunt id aspernatur exercitationem distinctio dolores cumque qui. Ut soluta facere dolorum minima et omnis provident. Qui accusantium aperiam inventore quia et eaque omnis officia. Tempora ea voluptatem nobis iste itaque voluptas provident. Rerum doloremque illo aut debitis. Omnis doloremque similique qui consequatur saepe. Laudantium molestiae consequuntur aperiam quidem. Velit qui ab autem distinctio odit. Ut fuga reiciendis doloremque consequuntur maxime molestiae aperiam quia.', 'Sed et ipsum sint. Et quaerat odit et hic minus. Enim aut labore est saepe veritatis deleniti velit doloribus.', '1', '2020-01-15 12:14:25', '2020-01-15 12:14:25', 49),
(40, 'https://pic.clubic.com/v1/images/434353/raw?', 'Sit ut praesentium.', 'Veniam saepe eius molestias nostrum vitae rerum expedita. Cum mollitia sunt ad temporibus magnam cumque fugiat sequi. Blanditiis est nihil libero quia. Officia est dolore sapiente dignissimos. Quibusdam velit id quis est. Officia voluptas aut quia molestiae minima culpa. Facere occaecati facilis sed beatae. Incidunt enim atque numquam earum. Facere et similique repellat et aut quae doloremque. Quo saepe accusamus voluptatem quia autem quisquam. Ex et blanditiis praesentium beatae incidunt unde minus. Corporis maxime quasi culpa eos provident rerum. Corrupti doloremque aut sunt architecto in. Nesciunt minima quo repudiandae et et. Praesentium voluptatum necessitatibus minima voluptatum ullam. Consectetur ut dolores architecto perspiciatis sed.', 'Nostrum odit praesentium doloribus. Doloribus esse eveniet veniam iure tenetur vero.', '1', '2020-01-15 12:14:25', '2020-01-15 12:14:25', 18),
(44, 'https://pic.clubic.com/v1/images/928689/raw?', 'Saepe nemo fugit et.', 'Et ex eum enim. Enim adipisci aliquam est sed quia id laboriosam. Quidem rerum tempore magnam quia quis rerum. Iusto molestias voluptas laudantium repellendus harum veniam aut dolores. Sunt dolorum accusantium molestiae asperiores quas illo non. Autem dolores dolores provident sed perferendis molestias. Voluptas facere veniam odio eaque molestiae eaque possimus. Non facere molestiae nihil unde illum sint. Est consequatur atque sit eveniet vel ratione voluptas. Debitis illo repudiandae nostrum ad exercitationem fugiat et. Hic laudantium et non reiciendis aut. Similique nobis sapiente quis nihil culpa error. Voluptates iure ad exercitationem hic tempora. Est blanditiis fugiat suscipit facere ut quisquam voluptas. Architecto explicabo dicta ut eum nemo iste et enim. Qui dicta similique dolore error quis. Repellendus ut aut explicabo eius dicta doloremque. Aut occaecati omnis iusto iusto tempora consectetur. Explicabo est eius expedita nobis beatae. Minus non voluptate quia fugiat eos nisi. Velit laudantium sed repellendus magni quia. Deserunt facere quia similique accusantium voluptatem qui sit. Vel alias deserunt iusto tempore et. Rerum accusamus quia autem eius commodi. Molestiae cupiditate sed eum nam quos id. Autem ea vitae reprehenderit nostrum pariatur.', 'Asperiores nemo veritatis veniam. Quis incidunt sint deserunt ut quo aut. Voluptas quia distinctio dolorem molestiae beatae.', '1', '2020-01-15 12:14:25', '2020-01-15 12:14:25', 17),
(45, 'https://pic.clubic.com/v1/images/128587/raw?', 'Eligendi molestiae ea.', 'Illo doloribus excepturi ut amet occaecati. Quod quo velit sint incidunt et omnis sint. Nam qui nesciunt beatae voluptas minima. Recusandae in occaecati cupiditate voluptatem quia voluptatem. Et incidunt neque at aspernatur odio quis sed fugit. Aut voluptatibus sed impedit quae ad. Illo mollitia maxime cumque eveniet ad. Nobis eos officiis sequi rerum. Nemo nulla repellendus totam laboriosam quia. Ut incidunt impedit inventore cumque consequuntur. Dolorem repudiandae eveniet officiis id quia ut nisi. Quaerat corrupti dolores illo ut. Est repellendus unde nihil consequatur ex illum. Sequi et hic velit consequuntur. Eos distinctio et maxime. Eligendi commodi consequuntur consectetur quidem. Quaerat ex voluptas minus sed architecto. Quis tenetur porro eveniet cupiditate. Quis non doloremque officia iste officiis animi voluptate. Consectetur maxime necessitatibus quo dolor consequatur. Natus soluta maxime aperiam officiis sit. Saepe quod qui tenetur odio alias omnis laboriosam.', 'Non aut libero quis molestias velit nisi. Adipisci eaque unde non illum quas. Quidem praesentium beatae eos doloremque necessitatibus nam beatae.', '1', '2020-01-15 12:14:25', '2020-01-15 12:14:25', 9);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(24) NOT NULL,
  `email` varchar(96) NOT NULL,
  `password` varchar(128) NOT NULL,
  `active` enum('0','1') DEFAULT '0',
  `name` varchar(50) NOT NULL,
  `city` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `twitter` varchar(50) DEFAULT NULL,
  `github` varchar(50) DEFAULT NULL,
  `bio` text DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT current_timestamp(),
  `update_time` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_UNIQUE` (`id`),
  UNIQUE KEY `email_UNIQUE` (`email`),
  UNIQUE KEY `username_UNIQUE` (`username`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `username`, `email`, `password`, `active`, `name`, `city`, `country`, `twitter`, `github`, `bio`, `avatar`, `create_time`, `update_time`) VALUES
(1, 'eric.denis', 'anne93@poulain.fr', '$2y$10$wfmFfMpQeEISynlHTMw9v.qPPQMaEw51e4FvXR2aKMhYaLpdbOG66', '1', 'Zoé Barbier', 'Rousseau', 'Argentine', NULL, NULL, 'Sapiente aliquid totam necessitatibus ducimus quam iure. Enim ut vel veniam earum. Fugit sint omnis doloremque maiores minus doloribus sed.', NULL, '1996-06-23 14:09:50', '2020-01-15 12:18:16'),
(2, 'rossi.elise', 'kbernard@perrier.fr', '$2y$10$qrDfzSKrAW8aMLiq97aPYephU4/85CzOK3u8MwN4emCwjRCkcHAma', '1', 'Isaac Neveu', 'Bernier-les-Bains', 'Guinée-Bissau', NULL, NULL, 'Voluptatem asperiores repellat nihil dolorem exercitationem unde et. Dicta aut ullam ab. Sunt et non ut.', NULL, '2015-12-20 11:38:38', '2020-01-15 12:18:16'),
(3, 'philippe02', 'josephine77@bourdon.org', '$2y$10$2NI9pcchP7Lw4Z0sFt5Nbuypvldhf0VJF1Rkd3yihBlgIYfAK2.SK', '1', 'Célina Payet', 'PiresVille', 'Saint Vincent et les Grenadines', NULL, NULL, 'Esse facilis velit maxime. Corporis est est mollitia qui aut vero sunt. Qui ullam sit possimus amet consequatur tempora expedita et.', NULL, '1990-04-28 17:08:06', '2020-01-15 12:18:16'),
(4, 'nathalie56', 'lucy39@voila.fr', '$2y$10$lGtWuy9exkKstURAyVnLieL.OahEEZ6nBVzrTVyCYIR4ZQi2Pkpay', '1', 'Henriette Le Blot', 'Barbier-les-Bains', 'Micronésie (États fédérés de)', NULL, NULL, 'Rerum ratione molestiae quo qui esse recusandae consequatur. Ut error est atque neque. Aut omnis illum dolores ipsa sequi amet omnis. Dolore rerum quam provident vel id error.', NULL, '2017-05-24 20:13:40', '2020-01-15 12:18:16'),
(5, 'richard76', 'hbecker@orange.fr', '$2y$10$J.kAfolE0/j8rdt/B0qS0uVUMecDBgp67VQSNDuGzM9HPDgKDoDWm', '1', 'Michèle Duval-Lenoir', 'Guerin-les-Bains', 'Bulgarie', NULL, NULL, 'Aut aut quam voluptatem magnam et. Qui repellat ut a commodi quam rem velit.', NULL, '1970-05-16 12:11:15', '2020-01-15 12:18:16'),
(6, 'alexandre.leroux', 'uduval@gaudin.org', '$2y$10$6WyWiNMp35DxWuqOTneSkeNOiRoA7lZJhGZULfaTwoJQCiOOXYsGS', '1', 'Margaret Mahe', 'Roche', 'Équateur', NULL, NULL, 'Eos qui ut recusandae et sit. Quis facilis officiis earum enim soluta.', NULL, '1972-01-29 20:29:10', '2020-01-15 12:18:16'),
(7, 'marie.jourdan', 'jfaivre@aubert.org', '$2y$10$w/6dUBKkLOiV.k0BNFwohOxsGId9dcLiQAioLK09MK.N36WNkZl8W', '1', 'Clémence-Juliette Gillet', 'Didier', 'Égypte', NULL, NULL, 'Sed maxime facilis consectetur aut iusto qui autem. Et aut eum optio consequatur omnis eius. Facere magnam quod non esse.', NULL, '1995-01-02 15:43:59', '2020-01-15 12:18:17'),
(8, 'dbouchet', 'raymond11@leconte.fr', '$2y$10$RaUKVSScNWxAUQNQDkV.IueefD60m9XQURU.slPnxoJeBJTfUse5u', '1', 'Luc Leveque', 'Gerard-sur-Giraud', 'Chili', NULL, NULL, 'Cum nesciunt pariatur iusto totam ex adipisci ducimus beatae. Exercitationem mollitia voluptas ea exercitationem.', NULL, '2015-09-01 07:07:57', '2020-01-15 12:18:17'),
(9, 'efernandes', 'claudine.rodrigues@garnier.com', '$2y$10$83r0l2xuiedL43WZLq1wZu3GxnyMMwFTBixp4CcMw46CG2FnXvLLy', '1', 'Colette Richard-Petitjean', 'Bonninboeuf', 'Albanie', NULL, NULL, 'Nemo voluptatem qui aut dignissimos sint. Sed ab perspiciatis minus earum.', NULL, '1999-09-27 20:12:18', '2020-01-15 12:18:17'),
(10, 'xboulanger', 'aime.bouvet@martin.net', '$2y$10$B/hpCe9BlpnhkVOTiPSKjevz7NNF6UUMI.LldczMk5aHiW50skvte', '1', 'Isabelle-Camille Dubois', 'Guyon-sur-Pinto', 'Pologne', NULL, NULL, 'Temporibus sed earum voluptas rem dolor esse aperiam. Molestiae repellendus soluta illum non laborum autem repudiandae dolor. Reprehenderit possimus ex et cupiditate veniam incidunt quos minus. Similique exercitationem labore dolor et et blanditiis.', NULL, '2009-02-18 04:45:03', '2020-01-15 12:18:17'),
(11, 'marguerite43', 'gerard18@sfr.fr', '$2y$10$b3/ILcQpDGAUc5Iadmkr1uCcLvbbSdfz7p1.ow951Q1DjGxp.ZNzG', '1', 'Corinne Carre', 'Lebreton-la-Forêt', 'Iran', NULL, NULL, 'Exercitationem ut eos eos corrupti suscipit. Enim magnam et deleniti temporibus adipisci. Voluptatum in voluptas aut veritatis.', NULL, '2002-04-27 08:54:21', '2020-01-15 12:18:17'),
(12, 'diane18', 'ymonnier@laposte.net', '$2y$10$xEWoLXTDPXbo72yQmH/CyOQL1f5ZQhBfESZyp4p8Y.VhismZQxnGu', '1', 'Maurice Denis', 'Parent', 'Inde', NULL, NULL, 'Fugiat magnam asperiores fugit. Ullam expedita non ut laudantium. Ullam cumque suscipit quia nisi molestiae debitis asperiores numquam. Est excepturi totam dolorem in adipisci unde. Cumque sint reprehenderit similique accusamus.', NULL, '2013-08-13 02:55:44', '2020-01-15 12:18:17'),
(13, 'hardy.daniel', 'leon.dumas@chauvin.com', '$2y$10$ZZn9g224Z/hRZWaJXjzTvu7oXfapJdrKxBzGFmjRRWOQoh/VV2g46', '1', 'Aimé Turpin', 'Fleury', 'Nouvelle-Zélande', NULL, NULL, 'Aspernatur autem dolorem aut molestias ut quis. Rem sit harum eum eos illo est. In qui qui natus voluptates.', NULL, '1971-02-09 02:24:45', '2020-01-15 12:18:17'),
(14, 'robert24', 'devaux.thibaut@daniel.com', '$2y$10$7qFkpcR9IVfGr0SsdTQn1.PhqWsY406J1dn2rkPFc09iepv4g1ZoO', '1', 'Catherine Marie', 'Hoarau', 'Svalbard et Jan Mayen (Îles)', NULL, NULL, 'Corrupti cupiditate adipisci qui atque. Asperiores quia dignissimos cum aut voluptatem. Minus aliquam autem nemo et. Placeat quasi esse tenetur nostrum nihil.', NULL, '2004-04-10 11:55:14', '2020-01-15 12:18:17'),
(15, 'colette92', 'veronique.pasquier@regnier.fr', '$2y$10$cDwSFvvVfLwmc4aRTqzcIubj7CbSYGpYHHh8mcQOJHwn9FGsIQtQ6', '1', 'Jean-Roger Charles', 'Valette', 'Afrique du sud', NULL, NULL, 'Ut totam quod et qui vitae a similique. Non libero voluptas est eligendi officiis. Autem sint est atque earum eos.', NULL, '2005-04-21 16:24:44', '2020-01-15 12:18:17'),
(16, 'diane04', 'amallet@orange.fr', '$2y$10$R.Zp0ev7KX7LPeLYMADtJe9TrE/Ly1QIxPJqEOHeT6zmf4KNXdHRe', '1', 'Marie Regnier', 'Valentin-sur-Ledoux', 'Mongolie', NULL, NULL, 'Officia ut enim odio. Molestiae et asperiores corporis dolore ducimus consequatur consequatur. Natus ab a architecto ea. Adipisci est sed nostrum repudiandae ipsam officiis.', NULL, '1994-11-02 05:22:13', '2020-01-15 12:18:17'),
(17, 'laroche.marthe', 'benjamin.foucher@michel.fr', '$2y$10$M49cjNcwmYrxg5x44iFb0.5QcY1wYV7t7OaSRJUKc7eRwq.50bX0q', '1', 'Yves Marchand', 'Deschamps-sur-Mer', 'Lithuanie', NULL, NULL, 'Et cupiditate et deserunt optio accusamus velit. Nemo consequatur non asperiores saepe. Et autem fugiat quae dolorum dolorem voluptas accusamus sed. Necessitatibus et veniam et minima vel est ut. Corporis dolorem nihil quia iste ut inventore.', NULL, '1997-07-29 01:35:17', '2020-01-15 12:18:17'),
(18, 'gallet.benjamin', 'wweiss@orange.fr', '$2y$10$00vV.OCtjR3.xP7yGNeXuuqcIGXvCJ4HMQq6me.JIvCBwrRXW./lm', '1', 'Alice Jacquot', 'Pages-la-Forêt', 'Bahrain', NULL, NULL, 'Nihil veniam et temporibus et tempore aut eligendi. Quia velit perferendis assumenda est quo sed dolorem aut. Ut accusantium nesciunt expedita aut. Omnis in voluptates suscipit laudantium ipsa consequatur nam. Corrupti quos sunt rerum animi.', NULL, '1981-10-23 02:40:32', '2020-01-15 12:18:17'),
(19, 'delahaye.stephane', 'herve.lucy@marchand.com', '$2y$10$u9RqYWbld8R7hi.qjbu8AeHP0h/0Yf2ga6.DHPzEIwPS3ntrBGuVO', '1', 'Geneviève Leconte', 'Girard', 'Portugal', NULL, NULL, 'Sint ab laboriosam asperiores laudantium ut accusamus. Velit quasi ut enim inventore. Consequatur enim perspiciatis non magni.', NULL, '2014-10-02 15:03:56', '2020-01-15 12:18:17'),
(20, 'adam.patrick', 'laure56@tele2.fr', '$2y$10$fF0UpuN19F759EviCp8mduc1YqZbSms109/RSzcrzWkjNbiKdCkVS', '1', 'Théodore Pereira', 'Bigot-la-Forêt', 'Tuvalu', NULL, NULL, 'Et totam nulla id et laboriosam possimus soluta. Iusto aut dignissimos asperiores. Temporibus placeat animi ut. Rem aut omnis aperiam officia ipsum laudantium.', NULL, '1973-03-26 14:34:28', '2020-01-15 12:18:17'),
(21, 'charles.dumas', 'bonnet.theophile@club-internet.fr', '$2y$10$XgRNn06XQVfH/Ug7KWVVp.ZBJ6KfbSWdERiDHS9SrBoNVA2ObJbV.', '1', 'Danielle-Agnès Berger', 'Gomez', 'Bolivie', NULL, NULL, 'Magnam nihil nobis ut. Possimus odio eveniet nobis iste. Dolor perspiciatis numquam a nam provident. Commodi non voluptatem velit neque possimus.', NULL, '1999-02-26 14:20:04', '2020-01-15 12:18:17'),
(22, 'lpires', 'weiss.alexandre@dbmail.com', '$2y$10$egLmJG3/Pzkr/4BVKF3T1.45N6bwAb1gAKXuiMDCCEW8CN2pTXFma', '1', 'Aimé Gauthier', 'BretonVille', 'Heard et McDonald (Îles)', NULL, NULL, 'Earum ut perspiciatis reiciendis qui porro consequatur impedit. Quas deleniti ipsa eaque. Quo eligendi doloribus numquam iure. Sunt dolor facere quia debitis.', NULL, '2009-06-22 03:33:29', '2020-01-15 12:18:18'),
(23, 'gchauvin', 'dvallee@orange.fr', '$2y$10$XTknzaICEIDBcbbvUILtiugrl9NVWp4J.Kqd5jlhfhdlGs4gV0yam', '1', 'Catherine-Diane Lebreton', 'Costenec', 'Samoa', NULL, NULL, 'Dolores incidunt cupiditate delectus vero quas. Nihil delectus magnam dolorem recusandae tempore. Ad vero error nisi aut modi officia et ut.', NULL, '2005-10-30 22:24:04', '2020-01-15 12:18:18'),
(24, 'ndevaux', 'dumas.philippe@remy.fr', '$2y$10$iq7tW3/9WErQ6CnW6hBwrOfVjg0SnVSpe7OlwcNm/Y5ISbrMZzKYa', '1', 'Thibault Masse', 'Thomas', 'Brunei', NULL, NULL, 'Ut et incidunt dolor recusandae rem cum enim non. Voluptatem ut laborum maxime nemo et ea quia. Atque qui ab qui. Magnam omnis accusantium culpa reiciendis.', NULL, '1978-10-08 17:02:26', '2020-01-15 12:18:18'),
(25, 'rousset.alix', 'edith26@guerin.fr', '$2y$10$.ha8uqFdylKrMWFntSRPqOJJ09/Q5khZwkvhGE9u/1/RaSfXxqIdW', '1', 'Philippe Leroy', 'Lejeuneboeuf', 'Groenland', NULL, NULL, 'Sequi quidem magnam eum qui dolorem sit porro. Iste et labore rerum facere quia id dolores. Sit tempore quam sunt dolore dolores alias. Nihil culpa id laudantium et error quo repellat sit. Dolores possimus repellat harum atque deserunt.', NULL, '1996-08-26 21:14:58', '2020-01-15 12:18:18'),
(26, 'margot38', 'bonnin.bertrand@allain.fr', '$2y$10$hyaSDF80O1qF5QOizMitCe/h3LyXp2wsXSVZNS.BbP0ePzHC0p1gO', '1', 'Honoré Boucher', 'BlotVille', 'Géorgie', NULL, NULL, 'Dicta qui aut quas et. In et sed sequi molestiae ut nisi et. Unde adipisci aliquid illo eaque. In aliquam consequatur possimus beatae atque ipsum voluptatibus consectetur.', NULL, '2001-04-10 23:34:29', '2020-01-15 12:18:18'),
(27, 'martin.jacques', 'josephine.brunet@becker.net', '$2y$10$L8LVmEJwE1BVmc401jIi/ePitRs8L/DeiqaFBeD0.zORQzL0Zk6Ki', '1', 'Alice Grenier-Lelievre', 'Joubert', 'États-Unis', NULL, NULL, 'Illo quod nesciunt assumenda eveniet qui nam reprehenderit. Mollitia quae dignissimos reiciendis ab beatae quam. Corrupti reiciendis accusamus qui id cumque corrupti.', NULL, '1974-05-01 23:41:22', '2020-01-15 12:18:18'),
(28, 'colas.henriette', 'valette.thibaut@legoff.fr', '$2y$10$MIuwxByCY2HUoIWETy4GZ.uQ/xY7GoY.8RZkIC4LzGKF26K43JDHq', '1', 'Lucie Hubert', 'Rodriguez-sur-Leblanc', 'Sierra Leone', NULL, NULL, 'Enim laudantium consequatur id quo sapiente culpa ea aut. Dolor sunt omnis impedit voluptatem repellat voluptas. Minus nobis inventore repudiandae corporis alias. Voluptas iusto ex sed. Voluptas non rerum eius est commodi rerum aut.', NULL, '2004-04-29 10:04:03', '2020-01-15 12:18:18'),
(29, 'rene.camus', 'lecomte.emilie@boyer.net', '$2y$10$BhtLjOjxW3H0BA49pRdDpetFXGA5ST2atschzCWh15iEl4SyIDRY.', '1', 'Henri Diaz', 'DelaunayBourg', 'Mariannes du Nord (Îles)', NULL, NULL, 'Eos et quam veniam placeat et deleniti et. Placeat aliquam possimus aut expedita ea consectetur inventore impedit. Possimus provident cupiditate commodi id. Quaerat quia numquam quas sed eligendi non. Assumenda animi assumenda rerum.', NULL, '2005-05-05 14:31:00', '2020-01-15 12:18:18'),
(30, 'lacroix.colette', 'upetitjean@noos.fr', '$2y$10$muJZixN1zda0kmC7pHJkkOTe59p2mqTSIOhZVmjiUL9CoIv6eDf3O', '1', 'Guy-Benoît Paul', 'Guyot', 'Arabie saoudite', NULL, NULL, 'Aperiam dicta animi blanditiis delectus dolorem et nesciunt. Sunt vitae beatae facere. Commodi aperiam molestiae praesentium ipsam saepe alias unde. Dicta laudantium veniam id repellendus.', NULL, '1974-10-29 11:53:32', '2020-01-15 12:18:18'),
(31, 'joseph18', 'cecile.vidal@baron.net', '$2y$10$pWFW80O7y5BIut4FvHFjCuzI5/PiOjHNIda3M14TQSCO8L04YuD8y', '1', 'Aimée Blanc-Durand', 'Hamel-sur-Mer', 'Maldives (Îles)', NULL, NULL, 'A quibusdam ducimus ducimus minima quaerat placeat quia. Rerum temporibus rerum officia a. Et aliquam nisi aut aperiam quia sit. Quisquam est praesentium consectetur explicabo.', NULL, '2006-12-23 05:24:18', '2020-01-15 12:18:18'),
(32, 'hugues21', 'gregoire.chretien@rocher.fr', '$2y$10$kfkNFPMwKir7c7pnSCeh6eoKFcEyiadJdW0w4Ug7vnZPt.TZ4/sWG', '1', 'Dominique Cousin', 'Renaudnec', 'Timor', NULL, NULL, 'Esse qui enim reprehenderit ipsam quaerat aut. Distinctio voluptatem laboriosam quia eos. Saepe nulla ut repellendus. Error blanditiis expedita nesciunt debitis a quo tenetur.', NULL, '1983-01-02 03:02:07', '2020-01-15 12:18:18'),
(33, 'zdurand', 'martine.andre@tiscali.fr', '$2y$10$.EGiYNyywU/mWjRtqKvyAuSBQYMA8z28T16e38vbc4wN.8fPkARJG', '1', 'Gilles Carlier', 'Schneider-sur-Fischer', 'Rwanda', NULL, NULL, 'Et dolore ut tenetur autem repellat sint sed. Iure cumque magnam qui et. Exercitationem velit omnis aut dolor consequuntur voluptatem. Vitae ex dolor eum velit voluptas.', NULL, '1997-11-08 12:27:32', '2020-01-15 12:18:18'),
(34, 'paulette58', 'antoine40@chauveau.com', '$2y$10$pTVtuK0BwinlPNw8Y2pv/Olb1OBCBrhQq9Yk6qXkPCXSQSz4jJ.re', '1', 'Henri Barthelemy', 'Lombard', 'Cayman (Îles)', NULL, NULL, 'Quia ab quisquam iusto. Voluptas a ea rerum nemo dignissimos tempore. Quidem voluptates iste in fuga sit qui.', NULL, '2005-03-31 20:16:31', '2020-01-15 12:18:18'),
(35, 'marie.patrick', 'emorel@sfr.fr', '$2y$10$IRCGZIszJ7ProjmykeVBr.ha00KK1PnksAeITKSNSDbWz0e/HNYLS', '1', 'Agathe Le Gonzalez', 'Martin', 'Espagne', NULL, NULL, 'Doloribus saepe nulla doloribus ut et iste. Qui quia consectetur sed sunt non animi qui. Unde consequuntur maxime recusandae accusamus odit fugit beatae debitis.', NULL, '1986-08-16 14:10:10', '2020-01-15 12:18:18'),
(36, 'leon28', 'barbier.eugene@roux.com', '$2y$10$wcRb6M4BICU/t6JX.pT3segI0MisWZr212gziKQ5OVoY82qp2IDLO', '1', 'René Bouvier', 'Cohen', 'Maroc', NULL, NULL, 'Aut vel voluptatum sunt nisi nihil quae sint. Dolor quis sint est veniam aut labore. Aperiam atque ea tempore quis aut suscipit pariatur. Blanditiis rerum tempora voluptas porro.', NULL, '1996-10-22 10:10:05', '2020-01-15 12:18:18'),
(37, 'besson.aurelie', 'louis.parent@leblanc.org', '$2y$10$A3d8XnK5pwFxWPiElraGkOnG4yqMhORd75yWzArir6h6tvOj2hcjm', '1', 'Christophe Paris', 'LaunayVille', 'Afghanistan', NULL, NULL, 'Perspiciatis id quia nihil aliquam. Odit quae est odit ipsa voluptates aperiam dicta. Architecto aut excepturi cum maxime reprehenderit.', NULL, '1978-12-23 06:31:17', '2020-01-15 12:18:19'),
(38, 'becker.luc', 'adrien.gillet@dijoux.fr', '$2y$10$ZMan4GluEs2xifh5bp2W.uv3AC03MAkBhRinVI2K..gBH4z/m5XKO', '1', 'Jean Marie', 'Hoarau-sur-Mer', 'Cook (Îles)', NULL, NULL, 'Molestias in rem nisi non animi quia laboriosam. Laborum aut ipsum reprehenderit vel est ea perferendis. Rem voluptas et et eius et minus. Aliquid quia ut omnis animi vel qui enim.', NULL, '1994-10-02 14:19:01', '2020-01-15 12:18:19'),
(39, 'philippine68', 'alphonse54@dasilva.net', '$2y$10$CCphH/Jy7Mtf5TY.GNucmuMpDuSnXM6IqlmcIcG6.98TfPZzcqcHe', '1', 'Patrick Faure', 'Roussel-les-Bains', 'Israël', NULL, NULL, 'Ipsum repellat ex qui quod. Distinctio aliquid enim necessitatibus veritatis fugiat facere. Aut est voluptas tempore sunt.', NULL, '2003-10-22 19:47:00', '2020-01-15 12:18:19'),
(40, 'jacqueline.fernandes', 'jvallee@gomes.fr', '$2y$10$XdhhK5tst.LDjpOfC/tZnusSTY6cv3amARS3.tXzrdFJ1HZUaALz2', '1', 'François Hoarau', 'HerveBourg', 'Belgique', NULL, NULL, 'Laboriosam explicabo vel distinctio aspernatur sapiente reprehenderit iusto. Vel maxime est laudantium excepturi qui omnis vero. Rem excepturi ea et molestias et nihil.', NULL, '1987-02-07 16:26:24', '2020-01-15 12:18:19'),
(41, 'frederique67', 'dufour.martine@club-internet.fr', '$2y$10$aAkVk3SxqXdCXDrHUbEP1O0QPA8UFNy1NlufeqzB24leZrCXTPE9C', '1', 'Audrey Georges', 'PineauVille', 'Hongrie', NULL, NULL, 'Praesentium et qui quibusdam odit mollitia ad accusantium. Sed veniam laborum aut sed dolorem. Omnis esse occaecati omnis necessitatibus ipsa. Magni et animi sed voluptates.', NULL, '1970-12-03 18:52:42', '2020-01-15 12:18:19'),
(42, 'laurent.arnaud', 'aurore36@michaud.org', '$2y$10$pd8TpbhO8qdFATlG6tpILO2bYRzeJekhFvr6Ih8BuipU1OGZLrDUi', '1', 'Léon Duhamel', 'Dupuy', 'Grenade', NULL, NULL, 'Commodi corporis hic et ab et eveniet. Atque voluptate modi excepturi. Tenetur laborum et ipsam rerum odio in praesentium quibusdam.', NULL, '1970-09-06 11:04:35', '2020-01-15 12:18:19'),
(43, 'carre.gabriel', 'julien05@faure.fr', '$2y$10$8U392LDAlMkuyYUW67gyGeqUtuBLAruGqhbc0D.qaFCm.xjStV.qe', '1', 'Frédéric Guillou-Gonzalez', 'Colin-sur-Joly', 'Zaïre', NULL, NULL, 'Nesciunt velit beatae et eos est. Perferendis tempora molestias qui et qui. Ut quam esse et dolores.', NULL, '1978-03-27 01:10:28', '2020-01-15 12:18:19'),
(44, 'jrenaud', 'roux.margaux@orange.fr', '$2y$10$ZWccLz9iC9CxnmMXwNa1Z.0UjfMwiY4BtGwjvlzU7dO4gKiO1yDpq', '1', 'Pauline de Bertrand', 'Maurice', 'Saint-Marin (Rép. de)', NULL, NULL, 'Esse architecto quibusdam repellat voluptas ipsam. Ipsum iure accusantium minus quibusdam unde voluptatem. Libero modi placeat reprehenderit totam. Sapiente necessitatibus ea accusamus velit iure et.', NULL, '1987-05-04 22:39:30', '2020-01-15 12:18:19'),
(45, 'fmartel', 'vallee.theodore@sfr.fr', '$2y$10$/Gw1kWK.oNOKtdOdk3AmOugAMxpqAdmuFYEPMDad1/k6FFFOOAW5y', '1', 'Laurent Royer', 'Hardy', 'Maurice', NULL, NULL, 'Nihil veniam vel ut nesciunt. Sed porro quaerat aut dolore natus.', NULL, '1995-02-12 02:56:56', '2020-01-15 12:18:19'),
(46, 'jacquot.ines', 'hortense96@noel.com', '$2y$10$iHRFTSznkiUe1i990WNRG.Jg5MNt0dKHo4z7VvQd8dRn8eLfhq2Wm', '1', 'Anouk-Valérie Bonnet', 'Blanc', 'Sainte Hélène', NULL, NULL, 'Fugit modi voluptatem quam unde. Repellendus quia officia officiis laboriosam. Nemo et eos ea unde cum voluptatum et.', NULL, '1970-11-18 03:53:50', '2020-01-15 12:18:19'),
(47, 'lucas.corinne', 'cferrand@dasilva.fr', '$2y$10$b4qxmejDBCwpE/c2XfW..uHUvysKmvN4tKPX3IV8jUw5pbw/UeURi', '1', 'Noémi Colas', 'RossiVille', 'Martinique', NULL, NULL, 'Eos modi quibusdam distinctio fugit. Sit ullam eius quia quod. Fugiat molestias tempora nostrum non voluptatem consequuntur commodi. Ut sit ullam vel id qui.', NULL, '1986-01-05 01:34:39', '2020-01-15 12:18:19'),
(48, 'michelle20', 'rpruvost@perrier.com', '$2y$10$vVffFeUSSMjIUplcexIOquIdVnIRiUmh42oEO5izzqchb7I3PT1U2', '1', 'Jacqueline-Michèle Neveu', 'Adam', 'Italie', NULL, NULL, 'Non eligendi ut animi molestiae eius aut in. Voluptas consequatur saepe cupiditate fuga. Rerum sint expedita id repellendus.', NULL, '1997-02-10 15:42:05', '2020-01-15 12:18:19'),
(49, 'philippe.renard', 'gomes.corinne@noos.fr', '$2y$10$prsUCXTcJhCBB3.8fb74Je9a4yKu6F0enZhBvURzd.NNDW8MNGEEm', '1', 'Arthur Lebon', 'Maury', 'Liechtenstein', NULL, NULL, 'Eius maiores sunt accusantium exercitationem dolor quia tempore ab. Rerum voluptas voluptates est. Corrupti ut dicta dolorem quo id saepe temporibus. Sunt maxime quasi omnis et.', NULL, '1995-03-31 22:08:26', '2020-01-15 12:18:19'),
(50, 'fguillon', 'vpereira@guillaume.fr', '$2y$10$tkt4tnZQc.GaFSL12O28bewTf.u0KVdpw0JsQzCMXieTyKetQtOH6', '1', 'Martin Dupuis', 'Klein', 'Bahamas', NULL, NULL, 'Velit voluptatem tempora dignissimos repellat laudantium voluptatibus ipsum. Tempora dolores labore consequuntur eum facilis neque. Ut pariatur ut in. Facilis nesciunt architecto corporis qui totam.', NULL, '2010-08-03 04:28:45', '2020-01-15 12:18:19');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
